# Generated by Django 6.0.3 on 2026-08-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('xv_anos', 'XV años'), ('cumpleanos', 'Cumpleaños'), ('graduacion', 'Graduación'), ('corporativo', 'Corporativo'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('mensaje_bienvenida', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='eventos/portadas/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='eventos/logos/')),
                ('color_principal', models.CharField(default='#000000', max_length=7)),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7)),
                ('plantilla', models.CharField(default='default', max_length=50)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('permitir_videos', models.BooleanField(default=False)),
                ('moderacion_activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('codigo_acceso', models.CharField(max_length=6)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='eventos.evento')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'numero'), name='unique_mesa_por_evento')],
            },
        ),
    ]
