# Generated by Django 6.0.3 on 2026-08-17 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=500)),
                ('nombre_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('tamaño', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='eventos.evento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='eventos.mesa')),
            ],
            options={
                'ordering': ['-creada_en'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'hash_sha256'), name='unique_foto_por_evento')],
            },
        ),
    ]
