# Generated by Django 6.0.3 on 2026-08-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='eliminada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='foto',
            name='uploader_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
