# Generated by Django 6.0.3 on 2026-08-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_foto_eliminada_at_foto_estado_foto_uploader_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='propietario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
