# Generated by Django 6.0.3 on 2026-08-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen_portada_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='evento',
            name='logo_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
