# Generated by Django 6.0.3 on 2026-08-18 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_imagen_portada_key_evento_logo_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='anfitriones',
            field=models.ManyToManyField(blank=True, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
