# Generated by Django 6.0.3 on 2026-08-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_anfitriones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='propietario',
        ),
    ]
