# Generated by Django 6.0.3 on 2026-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_invitacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fin_planeado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='upload_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
