# Generated by Django 6.0.3 on 2026-09-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_evento_available_until_evento_fin_planeado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(max_length=500, unique=True)),
                ("nombre_original", models.CharField(max_length=255)),
                ("content_type_declarado", models.CharField(max_length=100)),
                ("tamaño_declarado", models.PositiveBigIntegerField()),
                ("hash_declarado", models.CharField(max_length=64)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("cancelled", "Cancelada"),
                            ("expired", "Expirada"),
                            ("cleanup_pending", "Limpieza pendiente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tamaño_real",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_intents",
                        to="eventos.evento",
                    ),
                ),
                (
                    "foto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_intent",
                        to="eventos.foto",
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_intents",
                        to="eventos.mesa",
                    ),
                ),
            ],
        ),
    ]
