# Generated by Django 6.0.3 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_uploadintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadintent",
            name="final_object_key",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="finalizing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="source_etag",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="uploadintent",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("finalizing", "Materializando"),
                    ("confirmed", "Confirmada"),
                    ("cancelled", "Cancelada"),
                    ("expired", "Expirada"),
                    ("cleanup_pending", "Limpieza pendiente"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
