# Generated by Django 6.0.3 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_uploadintent_cleaned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emotiva', 'Emotiva'), ('fotografo', 'Saca al fotógrafo que llevas dentro'), ('instrucciones', 'Instrucciones')], max_length=20, unique=True)),
                ('titulo_interno', models.CharField(max_length=200)),
                ('imagen_key', models.CharField(blank=True, editable=False, max_length=500)),
                ('activa', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', 'tipo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('orden__gte', 1), ('orden__lte', 3)), name='slideshow_promo_orden_entre_1_y_3'), models.CheckConstraint(condition=models.Q(('activa', False), models.Q(('imagen_key', ''), _negated=True), _connector='OR'), name='slideshow_promo_activa_requiere_imagen')],
            },
        ),
    ]
