# Generated by Django 6.0.3 on 2026-09-11 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_evento_configuracion_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AceptacionLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_terminos', models.CharField(max_length=32)),
                ('version_privacidad', models.CharField(max_length=32)),
                ('aceptado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_legales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-aceptado_en', '-pk'),
            },
        ),
    ]
