# Generated by Django 6.0.3 on 2026-09-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_aceptacionlegal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creation_source',
            field=models.CharField(blank=True, choices=[('legacy', 'Legacy'), ('admin', 'Administración'), ('self_service', 'Autoservicio')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='self_service_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_autoservicio_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
