# Generated by Django 6.0.3 on 2026-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_uploadintent_uploader_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='media_access',
            field=models.CharField(choices=[('public', 'Público'), ('password', 'Protegido con contraseña')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='media_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
